#pragma once

#define HAPANEL_DISPLAY_WIDTH 480
#define HAPANEL_DISPLAY_HEIGHT 480

#define HAPANEL_STATUS_BAR_HEIGHT 36
#define HAPANEL_SPACE_XS 8
#define HAPANEL_SPACE_SM 16
#define HAPANEL_SPACE_MD 24
#define HAPANEL_SPACE_LG 36
#define HAPANEL_SPACE_XL 56

#define HAPANEL_RADIUS_SM 12
#define HAPANEL_RADIUS_MD 20
#define HAPANEL_RADIUS_LG 28

#define HAPANEL_ICON_STATUS 20
#define HAPANEL_ICON_SMALL 32
#define HAPANEL_ICON_MEDIUM 48
#define HAPANEL_ICON_LARGE 56
#define HAPANEL_ICON_HERO 80
